name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '1'
    - name: Run a multi-line script
      run: |
#        cd $GITHUB_WORKSPACE/community-operators-submodules-upstream-ripsaw,
        cat OWNERS
        echo test, and deploy your project.
